# Naysayer -> Ghostty theme
# Background / foreground taken from naysayer's let bindings
palette = 0=#062329
palette = 1=#F92672
palette = 2=#A6E22E
palette = 3=#E6DB74
palette = 4=#66D9EF
palette = 5=#FD5FF0
palette = 6=#A1EFE4
palette = 7=#D1B897

palette = 8=#126367
palette = 9=#FD971F
palette = 10=#C1D1E3
palette = 11=#E6DB74
palette = 12=#AE81FF
palette = 13=#7AD0C6
palette = 14=#A1EFE4
palette = 15=#FFFFFF

background = #062329
foreground = #D1B897

# Cursor & selection
cursor-color = #FFFFFF
cursor-text = #062329
selection-background = #0000FF
selection-foreground = #D1B897
