# vscode light palette scheme for Kitty
# By https://github/mofiqul

foreground=#000000
background=#ffffff
selection-foreground=#000000
selection-background=#d7ba7d
# url_color             #0087BD
# cursor_shape=beam
# black
palette=0=#000000
palette=8=#808080

# red
palette=1=#c72e0f
palette=9=#c72e0f

# green
palette=2=#008000
palette=10=#008000

# yellow
palette=3=#795e25
palette=11=#795e25

# blue
palette=4=#007acc
palette=12=#007acc

# magenta
palette=5=#af00db
palette=13=#af00db

# cyan
palette=6=#56b6c2
palette=14=#56b6c2

# white
palette=7=#000000
palette=15=#000000

